# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: execute npm test 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ matrix.node-version }}
    - name: Install
      uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
      with:
        args: npm install
    - name: Test
      uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
      with:
        args: npm run test
    # - run: npm install
    # - run: npm test